#==================================================
# Common Information
#==================================================

#==================================================
# File Upload Configuration
#==================================================
fileupload.maxUploadSize=100000
fileupload.maxUploadSizePerFile=1000000


#===================================================
# Datasource Configuration
#===================================================
#jdbc.driver=com.mysql.cj.jdbc.Driver
#jdbc.url=jdbc:mysql://localhost:3306/pubmed
#jdbc.username=root
#jdbc.password=0000

#jdbc.database.type=mysql
jdbc.driver=org.postgresql.Driver
jdbc.url=jdbc:postgresql://54.180.79.247:5432/postgres
jdbc.username=pubmeduser
jdbc.password=111111
jdbc.initialSize=5
jdbc.minIdle=5
jdbc.maxIdle=30
jdbc.maxTotal=40
jdbc.maxWaitMillis=3000
jdbc.validationQuery=SELECT 1
jdbc.testWhileIdle=true
jdbc.timeBetweenEvictionRunsMillis=1500000
jdbc.defaultAutoCommit=false